using Domain.Assets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Persistence.Configurations.Security;

public class AssetEntityConfiguration : IEntityTypeConfiguration<Asset>
{
    public void Configure(EntityTypeBuilder<Asset> builder)
    {

        builder.HasData(
            new Asset
            {
                Id = 1,
                Name = "Art Piece 1",
                TokenId = 1,
                Description = "A beautiful art piece by John Doe",
                Image = "https://example.com/image1.jpg",
                Video = null,
                Audio = null,
                OwnerId = "123e4567-e89b-12d3-a456-426614174000",
                CreatorId = "123e4567-e89b-12d3-a456-426614174000",
                Category = AssetCategory.art,
                Price = 1.0,
                AuctionId = 1,
                CollectionId = 1,
                Royalty = 0.1f,
                Likes = 10,
                TransactionHash = "hash1",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 2,
                Name = "Photograph 1",
                TokenId = 2,
                Description = "A stunning photograph by Jane Doe",
                Image = "https://example.com/image2.jpg",
                Video = null,
                Audio = null,
                OwnerId = "111e2222-e89b-12d3-a456-426614174001",
                CreatorId = "111e2222-e89b-12d3-a456-426614174001",
                Category = AssetCategory.photography,
                Price = 2.0,
                AuctionId = 2,
                CollectionId = 2,
                Royalty = 0.2f,
                Likes = 20,
                TransactionHash = "hash2",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 3,
                Name = "Design 1",
                TokenId = 3,
                Description = "An innovative design by Bob Smith",
                Image = "https://example.com/image3.jpg",
                Video = null,
                Audio = null,
                OwnerId = "333e4444-e89b-12d3-a456-426614174002",
                CreatorId = "333e4444-e89b-12d3-a456-426614174002",
                Category = AssetCategory.design,
                Price = 3.0,
                AuctionId = 3,
                CollectionId = 3,
                Royalty = 0.3f,
                Likes = 30,
                TransactionHash = "hash3",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 4,
                Name = "Music Track 1",
                TokenId = 4,
                Description = "A catchy music track by Alice Jones",
                Image = null,
                Video = null,
                Audio = "https://example.com/audio1.mp3",
                OwnerId = "444e5555-e89b-12d3-a456-426614174003",
                CreatorId = "444e5555-e89b-12d3-a456-426614174003",
                Category = AssetCategory.audio,
                Price = 4.0,
                AuctionId = 4,
                CollectionId = 4,
                Royalty = 0.4f,
                Likes = 40,
                TransactionHash = "hash4",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 5,
                Name = "Video 1",
                TokenId = 5,
                Description = "An entertaining video by Charlie Brown",
                Image = null,
                Video = "https://example.com/video1.mp4",
                Audio = null,
                OwnerId = "555e6666-e89b-12d3-a456-426614174004",
                CreatorId = "555e6666-e89b-12d3-a456-426614174004",
                Category = AssetCategory.video,
                Price = 5.0,
                AuctionId = 5,
                CollectionId = 5,
                Royalty = 0.5f,
                Likes = 50,
                TransactionHash = "hash5",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 6,
                Name = "3D Art 1",
                TokenId = 6,
                Description = "An impressive 3D art piece by David Davis",
                Image = "https://example.com/image6.jpg",
                Video = null,
                Audio = null,
                OwnerId = "666e7777-e89b-12d3-a456-426614174005",
                CreatorId = "666e7777-e89b-12d3-a456-426614174005",
                Category = AssetCategory.three_d,
                Price = 6.0,
                AuctionId = 6,
                CollectionId = 6,
                Royalty = 0.6f,
                Likes = 60,
                TransactionHash = "hash6",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 7,
                Name = "eBook 1",
                TokenId = 7,
                Description = "An informative eBook by Evelyn Green",
                Image = "https://example.com/image7.jpg",
                Video = null,
                Audio = null,
                OwnerId = "777e8888-e89b-12d3-a456-426614174006",
                CreatorId = "777e8888-e89b-12d3-a456-426614174006",
                Category = AssetCategory.ebook,
                Price = 7.0,
                AuctionId = 7,
                CollectionId = 7,
                Royalty = 0.7f,
                Likes = 70,
                TransactionHash = "hash7",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 8,
                Name = "Ticket 1",
                TokenId = 8,
                Description = "A ticket to an exclusive event by Frank Franklin",
                Image = "https://example.com/image8.jpg",
                Video = null,
                Audio = null,
                OwnerId = "888e9999-e89b-12d3-a456-426614174007",
                CreatorId = "888e9999-e89b-12d3-a456-426614174007",
                Category = AssetCategory.ticket,
                Price = 8.0,
                AuctionId = 8,
                CollectionId = 8,
                Royalty = 0.8f,
                Likes = 80,
                TransactionHash = "hash8",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 9,
                Name = "Art Piece 2",
                TokenId = 9,
                Description = "A captivating art piece by Grace Gray",
                Image = "https://example.com/image9.jpg",
                Video = null,
                Audio = null,
                OwnerId = "999e0000-e89b-12d3-a456-426614174008",
                CreatorId = "999e0000-e89b-12d3-a456-426614174008",
                Category = AssetCategory.art,
                Price = 9.0,
                AuctionId = 9,
                CollectionId = 9,
                Royalty = 0.9f,
                Likes = 90,
                TransactionHash = "hash9",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 10,
                Name = "Photograph 2",
                TokenId = 10,
                Description = "A breathtaking photograph by Henry Hall",
                Image = "https://example.com/image10.jpg",
                Video = null,
                Audio = null,
                OwnerId = "000e1111-e89b-12d3-a456-426614174009",
                CreatorId = "000e1111-e89b-12d3-a456-426614174009",
                Category = AssetCategory.photography,
                Price = 10.0,
                AuctionId = 10,
                CollectionId = 10,
                Royalty = 1.0f,
                Likes = 100,
                TransactionHash = "hash10",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 11,
                Name = "Design 2",
                TokenId = 11,
                Description = "A sleek design by Iggy Iglesias",
                Image = "https://example.com/image11.jpg",
                Video = null,
                Audio = null,
                OwnerId = "111e2222-e89b-12d3-a456-426614174010",
                CreatorId = "111e2222-e89b-12d3-a456-426614174010",
                Category = AssetCategory.design,
                Price = 11.0,
                AuctionId = 11,
                CollectionId = 11,
                Royalty = 0.11f,
                Likes = 110,
                TransactionHash = "hash11",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 12,
                Name = "Music Track 2",
                TokenId = 12,
                Description = "A soulful music track by Jessie James",
                Image = null,
                Video = null,
                Audio = "https://example.com/audio12.mp3",
                OwnerId = "222e3333-e89b-12d3-a456-426614174011",
                CreatorId = "222e3333-e89b-12d3-a456-426614174011",
                Category = AssetCategory.audio,
                Price = 12.0,
                AuctionId = 12,
                CollectionId = 12,
                Royalty = 0.12f,
                Likes = 120,
                TransactionHash = "hash12",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 13,
                Name = "Video 2",
                TokenId = 13,
                Description = "A thought-provoking video by Karl Kennedy",
                Image = null,
                Video = "https://example.com/video13.mp4",
                Audio = null,
                OwnerId = "333e4444-e89b-12d3-a456-426614174012",
                CreatorId = "333e4444-e89b-12d3-a456-426614174012",
                Category = AssetCategory.video,
                Price = 13.0,
                AuctionId = 13,
                CollectionId = 13,
                Royalty = 0.13f,
                Likes = 130,
                TransactionHash = "hash13",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 14,
                Name = "3D Art 2",
                TokenId = 14,
                Description = "A mesmerizing 3D art piece by Lucy Lu",
                Image = "https://example.com/image14.jpg",
                Video = null,
                Audio = null,
                OwnerId = "444e5555-e89b-12d3-a456-426614174013",
                CreatorId = "444e5555-e89b-12d3-a456-426614174013",
                Category = AssetCategory.three_d,
                Price = 14.0,
                AuctionId = 14,
                CollectionId = 14,
                Royalty = 0.14f,
                Likes = 140,
                TransactionHash = "hash14",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 15,
                Name = "eBook 2",
                TokenId = 15,
                Description = "An insightful eBook by Mike Miller",
                Image = "https://example.com/image15.jpg",
                Video = null,
                Audio = null,
                OwnerId = "555e6666-e89b-12d3-a456-426614174014",
                CreatorId = "555e6666-e89b-12d3-a456-426614174014",
                Category = AssetCategory.ebook,
                Price = 15.0,
                AuctionId = 15,
                CollectionId = 15,
                Royalty = 0.15f,
                Likes = 150,
                TransactionHash = "hash15",
                Status = AssetStatus.OnAuction
            },
            new Asset
            {
                Id = 16,
                Name = "Art Piece 3",
                TokenId = 16,
                Description = "A unique art piece by John Doe",
                Image = "https://example.com/image16.jpg",
                Video = null,
                Audio = null,
                OwnerId = "123e4567-e89b-12d3-a456-426614174000",
                CreatorId = "123e4567-e89b-12d3-a456-426614174000",
                Category = AssetCategory.art,
                Price = 16.0,
                AuctionId = null,
                CollectionId = null,
                Royalty = 0.16f,
                Likes = 160,
                TransactionHash = "hash16",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 17,
                Name = "Photograph 3",
                TokenId = 17,
                Description = "A rare photograph by Jane Doe",
                Image = "https://example.com/image17.jpg",
                Video = null,
                Audio = null,
                OwnerId = "111e2222-e89b-12d3-a456-426614174001",
                CreatorId = "111e2222-e89b-12d3-a456-426614174001",
                Category = AssetCategory.photography,
                Price = 17.0,
                AuctionId = null,
                CollectionId = 2,
                Royalty = 0.17f,
                Likes = 170,
                TransactionHash = "hash17",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 18,
                Name = "Design 3",
                TokenId = 18,
                Description = "A modern design by Bob Smith",
                Image = "https://example.com/image18.jpg",
                Video = null,
                Audio = null,
                OwnerId = "333e4444-e89b-12d3-a456-426614174002",
                CreatorId = "333e4444-e89b-12d3-a456-426614174002",
                Category = AssetCategory.design,
                Price = 18.0,
                AuctionId = null,
                CollectionId = null,
                Royalty = 0.18f,
                Likes = 180,
                TransactionHash = "hash18",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 19,
                Name = "Music Track 3",
                TokenId = 19,
                Description = "A popular music track by Alice Jones",
                Image = null,
                Video = null,
                Audio = "https://example.com/audio19.mp3",
                OwnerId = "444e5555-e89b-12d3-a456-426614174003",
                CreatorId = "444e5555-e89b-12d3-a456-426614174003",
                Category = AssetCategory.audio,
                Price = 19.0,
                AuctionId = null,
                CollectionId = 4,
                Royalty = 0.19f,
                Likes = 190,
                TransactionHash = "hash19",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 20,
                Name = "Video 3",
                TokenId = 20,
                Description = "A viral video by Charlie Brown",
                Image = null,
                Video = "https://example.com/video20.mp4",
                Audio = null,
                OwnerId = "555e6666-e89b-12d3-a456-426614174004",
                CreatorId = "555e6666-e89b-12d3-a456-426614174004",
                Category = AssetCategory.video,
                Price = 20.0,
                AuctionId = null,
                CollectionId = null,
                Royalty = 0.20f,
                Likes = 200,
                TransactionHash = "hash20",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 21,
                Name = "3D Art 3",
                TokenId = 21,
                Description = "A stunning 3D art piece by David Davis",
                Image = "https://example.com/image21.jpg",
                Video = null,
                Audio = null,
                OwnerId = "666e7777-e89b-12d3-a456-426614174005",
                CreatorId = "666e7777-e89b-12d3-a456-426614174005",
                Category = AssetCategory.three_d,
                Price = 21.0,
                AuctionId = null,
                CollectionId = 6,
                Royalty = 0.21f,
                Likes = 210,
                TransactionHash = "hash21",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 22,
                Name = "eBook 3",
                TokenId = 22,
                Description = "A best-selling eBook by Evelyn Green",
                Image = "https://example.com/image22.jpg",
                Video = null,
                Audio = null,
                OwnerId = "777e8888-e89b-12d3-a456-426614174006",
                CreatorId = "777e8888-e89b-12d3-a456-426614174006",
                Category = AssetCategory.ebook,
                Price = 22.0,
                AuctionId = null,
                CollectionId = null,
                Royalty = 0.22f,
                Likes = 220,
                TransactionHash = "hash22",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 23,
                Name = "Ticket 3",
                TokenId = 23,
                Description = "A ticket to a popular event by Frank Franklin",
                Image = "https://example.com/image23.jpg",
                Video = null,
                Audio = null,
                OwnerId = "888e9999-e89b-12d3-a456-426614174007",
                CreatorId = "888e9999-e89b-12d3-a456-426614174007",
                Category = AssetCategory.ticket,
                Price = 23.0,
                AuctionId = null,
                CollectionId = 8,
                Royalty = 0.23f,
                Likes = 230,
                TransactionHash = "hash23",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 24,
                Name = "Art Piece 4",
                TokenId = 24,
                Description = "A captivating art piece by Grace Gray",
                Image = "https://example.com/image24.jpg",
                Video = null,
                Audio = null,
                OwnerId = "999e0000-e89b-12d3-a456-426614174008",
                CreatorId = "999e0000-e89b-12d3-a456-426614174008",
                Category = AssetCategory.art,
                Price = 24.0,
                AuctionId = null,
                CollectionId = null,
                Royalty = 0.24f,
                Likes = 240,
                TransactionHash = "hash24",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 25,
                Name = "Photograph 4",
                TokenId = 25,
                Description = "A beautiful photograph by Henry Hall",
                Image = "https://example.com/image25.jpg",
                Video = null,
                Audio = null,
                OwnerId = "000e1111-e89b-12d3-a456-426614174009",
                CreatorId = "000e1111-e89b-12d3-a456-426614174009",
                Category = AssetCategory.photography,
                Price = 25.0,
                AuctionId = null,
                CollectionId = 10,
                Royalty = 0.25f,
                Likes = 250,
                TransactionHash = "hash25",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 26,
                Name = "Design 4",
                TokenId = 26,
                Description = "An innovative design by Iggy Iglesias",
                Image = "https://example.com/image26.jpg",
                Video = null,
                Audio = null,
                OwnerId = "111e2222-e89b-12d3-a456-426614174010",
                CreatorId = "111e2222-e89b-12d3-a456-426614174010",
                Category = AssetCategory.design,
                Price = 26.0,
                AuctionId = null,
                CollectionId = 11,
                Royalty = 0.26f,
                Likes = 260,
                TransactionHash = "hash26",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 27,
                Name = "Music Track 4",
                TokenId = 27,
                Description = "A hit music track by Jessie James",
                Image = null,
                Video = null,
                Audio = "https://example.com/audio27.mp3",
                OwnerId = "222e3333-e89b-12d3-a456-426614174011",
                CreatorId = "222e3333-e89b-12d3-a456-426614174011",
                Category = AssetCategory.audio,
                Price = 27.0,
                AuctionId = null,
                CollectionId = null,
                Royalty = 0.27f,
                Likes = 270,
                TransactionHash = "hash27",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 28,
                Name = "Video 4",
                TokenId = 28,
                Description = "A viral video by Karl Kennedy",
                Image = null,
                Video = "https://example.com/video28.mp4",
                Audio = null,
                OwnerId = "333e4444-e89b-12d3-a456-426614174012",
                CreatorId = "333e4444-e89b-12d3-a456-426614174012",
                Category = AssetCategory.video,
                Price = 28.0,
                AuctionId = null,
                CollectionId = 13,
                Royalty = 0.28f,
                Likes = 280,
                TransactionHash = "hash28",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 29,
                Name = "3D Art 4",
                TokenId = 29,
                Description = "An impressive 3D art piece by Lucy Lu",
                Image = "https://example.com/image29.jpg",
                Video = null,
                Audio = null,
                OwnerId = "444e5555-e89b-12d3-a456-426614174013",
                CreatorId = "444e5555-e89b-12d3-a456-426614174013",
                Category = AssetCategory.three_d,
                Price = 29.0,
                AuctionId = null,
                CollectionId = null,
                Royalty = 0.29f,
                Likes = 290,
                TransactionHash = "hash29",
                Status = AssetStatus.NotOnSale
            },
            new Asset
            {
                Id = 30,
                Name = "eBook 4",
                TokenId = 30,
                Description = "A popular eBook by Mike Miller",
                Image = "https://example.com/image30.jpg",
                Video = null,
                Audio = null,
                OwnerId = "555e6666-e89b-12d3-a456-426614174014",
                CreatorId = "555e6666-e89b-12d3-a456-426614174014",
                Category = AssetCategory.ebook,
                Price = 30.0,
                AuctionId = null,
                CollectionId = 15,
                Royalty = 0.30f,
                Likes = 300,
                TransactionHash = "hash30",
                Status = AssetStatus.NotOnSale
            }
        );
    }
}