version: "3.8"

services:

  backend-api:
    build: ./Backend
    ports:
      - "5059:80"
      - "7087:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      ASPNETCORE_HTTPS_PORT: 443 
      NFT_MARKET_ConnectionStrings__AppConnectionStringRemote: 'User ID=<user>;Password=<password>;Server=<host>;Port=5432;Database=<database>;Integrated Security=true;Pooling=true;'

  # frontend:
  #   build: ./Front-end
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_BACKEND_API_URL: http://backend-api:8000 
