version: "3.8"

services:

  backend-api:
    build: ./Backend
    # ports:
    #   - "5999:80"

  # frontend:
  #   build: ./Front-end
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_BACKEND_API_URL: http://backend-api:8000 
