version: '3.8'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  api:
    image: api:latest
    depends_on:
      - "db"
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=db;port=5432;database=nft;username=nftuser;password=nftuser"
    networks:
      - dockerapi-dev  
  
  db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "nftuser"
      POSTGRES_PASSWORD: "nftuser"
      POSTGRES_DB: "nft"
    networks:
      - dockerapi-dev
volumes:
  db_volume:
         
    
     